// <auto-generated />
using System;
using GeoPath.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoPath.Infrastructure.Migrations
{
    [DbContext(typeof(GeoPathDbContext))]
    [Migration("20261009072052_InitialCoreDomain")]
    partial class InitialCoreDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoPath.Domain.AttemptStageResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "Stage")
                        .IsUnique();

                    b.ToTable("attempt_stage_results", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("ClassroomId", "LearnerId")
                        .IsUnique();

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinCodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JoinCodeHash")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.ExampleDefinition", b =>
                {
                    b.Property<Guid>("ExampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ExampleId", "DefinitionId");

                    b.HasIndex("DefinitionId");

                    b.ToTable("example_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            ExampleId = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c002"),
                            DefinitionId = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c004")
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.ExampleTheorem", b =>
                {
                    b.Property<Guid>("ExampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TheoremId")
                        .HasColumnType("uuid");

                    b.HasKey("ExampleId", "TheoremId");

                    b.HasIndex("TheoremId");

                    b.ToTable("example_theorems", (string)null);

                    b.HasData(
                        new
                        {
                            ExampleId = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c002"),
                            TheoremId = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c003")
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.GeometryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished", "Name");

                    b.ToTable("definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c004"),
                            Description = "A chord is a straight line segment joining two points on a circle.",
                            IsPublished = true,
                            Name = "Chord"
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.GeometryExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GuidedFlowJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("IsPublished", "Title");

                    b.ToTable("examples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "Medium",
                            IsPublished = true,
                            Prompt = "Identify the angles subtended by chord AB at points C and D on the same segment.",
                            Title = "Angles in the same segment",
                            TopicId = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c001")
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.GeometryTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c001"),
                            Description = "Angles, chords, and circle theorems.",
                            Name = "Circle geometry"
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.LearningAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByTeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByTeacherId");

                    b.HasIndex("ExampleId");

                    b.HasIndex("ClassroomId", "DueAtUtc");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.LearningAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId");

                    b.HasIndex("LearnerId", "StartedAtUtc");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.RoleDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Visitor",
                            Name = "Visitor"
                        },
                        new
                        {
                            Id = "Learner",
                            Name = "Learner"
                        },
                        new
                        {
                            Id = "Teacher",
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = "Author",
                            Name = "Author"
                        },
                        new
                        {
                            Id = "Admin",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.Theorem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished", "Name");

                    b.ToTable("theorems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef08a50d-dc56-47ab-9c99-2104ce69c003"),
                            Explanation = "The two angles stand on the same chord and lie in the same segment of the circle.",
                            IsPublished = true,
                            Name = "Angles in the same segment",
                            Statement = "Angles subtended by the same chord at the circumference, on the same segment, are equal."
                        });
                });

            modelBuilder.Entity("GeoPath.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GeoPath.Domain.AttemptStageResult", b =>
                {
                    b.HasOne("GeoPath.Domain.LearningAttempt", null)
                        .WithMany("StageResults")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.ClassEnrollment", b =>
                {
                    b.HasOne("GeoPath.Domain.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.Classroom", b =>
                {
                    b.HasOne("GeoPath.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.ExampleDefinition", b =>
                {
                    b.HasOne("GeoPath.Domain.GeometryDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.GeometryExample", "Example")
                        .WithMany("Definitions")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Example");
                });

            modelBuilder.Entity("GeoPath.Domain.ExampleTheorem", b =>
                {
                    b.HasOne("GeoPath.Domain.GeometryExample", "Example")
                        .WithMany("Theorems")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.Theorem", "Theorem")
                        .WithMany()
                        .HasForeignKey("TheoremId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Example");

                    b.Navigation("Theorem");
                });

            modelBuilder.Entity("GeoPath.Domain.GeometryExample", b =>
                {
                    b.HasOne("GeoPath.Domain.GeometryTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("GeoPath.Domain.LearningAssignment", b =>
                {
                    b.HasOne("GeoPath.Domain.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.GeometryExample", null)
                        .WithMany()
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.LearningAttempt", b =>
                {
                    b.HasOne("GeoPath.Domain.GeometryExample", null)
                        .WithMany()
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPath.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.User", b =>
                {
                    b.HasOne("GeoPath.Domain.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoPath.Domain.GeometryExample", b =>
                {
                    b.Navigation("Definitions");

                    b.Navigation("Theorems");
                });

            modelBuilder.Entity("GeoPath.Domain.LearningAttempt", b =>
                {
                    b.Navigation("StageResults");
                });
#pragma warning restore 612, 618
        }
    }
}
