<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GeoPath.Application/GeoPath.Application.csproj" />
    <ProjectReference Include="../GeoPath.Domain/GeoPath.Domain.csproj" />
  </ItemGroup>

</Project>
